### ISSUE TITLE
CloudLibrary App shifting text to the right in every chapter

### ISSUE THREAD

**Issue by ice1080** [BibliothecaTeam/Bibliotheca.Client#2]
When I use the CloudLibrary app, each chapter centers the text. But after that, each time I change pages to the next page, the text shifts approximately 1px to the left. After about 10 pages, the text begins to go off screen so for books that have chapters more than 10 screen-pages long, the text on the right is cut off and becomes more and more difficult to read.

I would be happy to assist with fixing this issue if I am pointed in the right direction of the relevant files for this issue.

Additional Info:
Pixel 2
Android Vesion 11

**Comment by mczachurski** [comment]
Hi, sorry but I don't know what CloudLibrary app is. Probably it's software created by someone else.
